### ISSUE TITLE
INVALID_ARGUMENT: Task.payload_type is not set.

### ISSUE THREAD

**Issue by steren** [googleapis/nodejs-tasks#203]
I upgraded to `"@google-cloud/tasks": "^0.5.0"`
I am using Node.js `v10.15.3` and deployed my Node.js application to Cloud Run.

I get this error:

In the past, I did not have to specify `payload_type`

```
Error: 3 INVALID_ARGUMENT: Task.payload_type is not set.
    at Object.exports.createStatusError (/usr/src/app/node_modules/@google-cloud/tasks/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/usr/src/app/node_modules/@google-cloud/tasks/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/usr/src/app/node_modules/@google-cloud/tasks/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/usr/src/app/node_modules/@google-cloud/tasks/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/usr/src/app/node_modules/@google-cloud/tasks/node_modules/grpc/src/client_interceptors.js:845:24)
```

Here is the code I use to create my tasks:

```
'use strict';
const cloudTasks = require('@google-cloud/tasks');
const client = new cloudTasks.CloudTasksClient();

/** Create an HTTP task
 * @param {string} project GCP Project
 * @param {string} location queue location
 * @param {string} queue queue name
 * @param {string} url absolute URL
 */
async function createTask(project, location, queue, url) {
  const parent = client.queuePath(project, location, queue);

  const task = {
    httpRequest: {
      httpMethod: 'GET',
      url: url,
    },
  };
  const request = {
    parent: parent,
    task: task,
  };

  console.log(`Sending task ${url}`);
  await client.createTask(request);
};

exports.createTask = createTask;
```

**Comment by steren** [comment]
This error did not occur with version `0.4.0`

**Comment by averikitsch** [comment]
Hi Steren,
Unfortunately with the release of the GA version, V2 , you'll need to specify the version v2beta3 that has the HTTP target feature. See https://github.com/googleapis/nodejs-tasks/blob/master/samples/createHttpTask.js#L31

**Comment by steren** [comment]
I know this is a `0.x` release, but this is a breaking change for all users of this library. I consider this a bug.

**Comment by callmehiphop** [comment]
@steren when pre 1.0, semver says to use the minor field to make breaking changes. While this can be annoying, I don't think we should consider it a bug. If our default export is a stable version, maybe we should consider going 1.0 to prevent stuff like this in the future.

@bcoe any thoughts?

**Comment by bart-at-google** [comment]
Also, I believe this only breaks users of HTTP targets, which is currently an alpha feature.

**Comment by JustinBeckwith** [comment]
We get feedback like Steren's a fair bit.  While our treatment of `0.x` in semver is [technically correct](https://i.kym-cdn.com/photos/images/original/000/909/991/48c.jpg), it tends to confuse people.  I'd rather us start going 1.0 more eagerly (like, after the service is in beta), then just do major semver bumps when we do things like change the default exported version.  

The plan as of now is to take all of these `0.x` libraries to `1.0` in early May, after Node.js `6.x` goes EOL (it's a breaking change anyway).

**Comment by steren** [comment]
I want to note that that I was using an alpha feature so a breaking change like this is acceptable.

However, I am now concerned about the need to do `const {v2beta3} = require('@google-cloud/tasks');`.

**Comment by lkuich** [comment]
@averikitsch I am using `0.5.0` with:

```javascript
const {v2beta3} = require('@google-cloud/tasks');
const client = new v2beta3.CloudTasksClient();
```

And still getting `INVALID_ARGUMENT: Task.payload_type is not set`

**Comment by averikitsch** [comment]
Hi @lkuich - 
HTTP Targets for Cloud Tasks is still in alpha. To get access to the feature, please fill out this form https://docs.google.com/forms/d/e/1FAIpQLSfc4uEy9CBHKYUSdnY1hdhKDCX7julVZHy3imOiR-XrU7bUNQ/viewform?vc=0&c=0&w=1.

**Comment by lkuich** [comment]
Thanks @averikitsch, I have requested the feature. I didn't realize it was a closed-alpha

**Comment by philberg** [comment]
@averikitsch I know this isn't exactly the right place to ask this, but I can't find the answer anywhere else.

If I want to trigger a firebase cloud function (which has an exposed HTTPS endpoint) via a cloud task, I need to use the new `httpRequest` task that's in alpha, right?

**Comment by averikitsch** [comment]
@philberg Yes, you can use `httpRequest` to trigger your function. Just to note, this is not secure unless you add an authentication token. More information will be available when the product goes to beta.

**Comment by JustinBeckwith** [comment]
Greetings folks!  It looks like the original issue was resolved.  @steren you'll notice that 1.x is out now (as it will be for many of the npm modules we ship).  From here on out, the semverity of releases should be far more predictable :) Unless there are objections, I am going to go ahead and close this out.

**Comment by grant** [comment]
@averikitsch @JustinBeckwith 
I'm seeing the error:

```js
ERROR: Task.payload_type is not set.
```

When switching from `v2beta3` to `v2`.

My `createTask` request does not have or need an HTTP payload as stated in the error:

```js
    name,
    httpRequest: {
      httpMethod: 'GET',
      url: ...,
    },
```

Am I doing something wrong? Meanwhile, I'll keep using `v2beta3`.

**Comment by averikitsch** [comment]
`v2` hasn't been released for HTTP Targets. You have you use version: `v2beta3`.

**Comment by grant** [comment]
Can't we keep this issue open until this v2 supports this feature? Or at least link the public bug that is tracking this v2beta3 requirement?

Do we think that the error message is ideal?

This was reopened due to a bad suggestion in a recent review. I believe the error message isn't ideal even if this library doesn't attempt to modify it. Perhaps we can make the error message better in the core service.

**Comment by javorosas** [comment]
Has it been released?

> `v2` hasn't been released for HTTP Targets. You have you use version: `v2beta3`.

has it now? I still can't get it to work with `v2`

**Comment by averikitsch** [comment]
[Http Targets](https://googleapis.dev/nodejs/tasks/latest/google.cloud.tasks.v2.html#.Task) have been added to V2. You will need to update to the newest version 1.6.1. The [samples](https://github.com/googleapis/nodejs-tasks/blob/master/samples/createHttpTask.js) have been updated to reflect this.

**Comment by DjangoOverloard** [comment]
I get this error while having a payload, am I doing something wrong?
```
function generateTask(payload:any){
        const task: {[k:string]:any} = {}; 
        const httpRequest: {[k: string]: any} = {
            'httpMethod': 'POST',
            url, 
        };
        httpRequest.body = Buffer.from(JSON.stringify(payload)).toString('base64');
        task.httpRequest = httpRequest;
        task.scheduleTime = payload.time;
        return task;
    }
```

**Comment by averikitsch** [comment]
Can you confirm the version of the "@google-cloud/tasks" package? Also how are you instantiating a client? Are you using the default: `const {CloudTasksClient} = require('@google-cloud/tasks');` or using a version like v2, v2beta3, ..?

**Comment by JustinBeckwith** [comment]
@DjangoOverloard Could we trouble you to open a new GitHub issue?  It will make helping out a lot easier!
